# Brings up the throwaway test stack on Windows.
#
#   .\scripts\test-up.ps1
#
# Generates .env.test with random credentials on first run, validates the
# configuration, then starts the stack. Nothing to fill in by hand — the point
# is to see the project running without touching .env at all.
#
# .env.test is generated, never committed: .gitignore already covers .env.*

$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent $PSScriptRoot
Set-Location $repoRoot

$envFile = Join-Path $repoRoot '.env.test'
$composeArgs = @(
    '--env-file', $envFile,
    '-f', 'docker-compose.yml',
    '-f', 'docker-compose.test.yml'
)

# --- Docker must be running ------------------------------------------------

try {
    docker info --format '{{.ServerVersion}}' *> $null
    if ($LASTEXITCODE -ne 0) { throw }
}
catch {
    Write-Host 'Docker is not running. Start Docker Desktop and try again.' -ForegroundColor Red
    exit 1
}

# --- Credentials -----------------------------------------------------------

# Alphanumeric only, so no value can collide with the ways compose reads a
# .env file: `$` starts an interpolation and `#` starts a comment. The modulo
# below is very slightly biased; for a credential that exists only inside a
# localhost-only throwaway stack that does not matter.
function New-Secret {
    param([int]$Length = 32)
    $alphabet = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'
    $bytes = New-Object 'byte[]' $Length
    $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    try { $rng.GetBytes($bytes) } finally { $rng.Dispose() }
    -join ($bytes | ForEach-Object { $alphabet[$_ % $alphabet.Length] })
}

if (-not (Test-Path $envFile)) {
    Write-Host 'Generating .env.test with random credentials...' -ForegroundColor Cyan

    $lines = @(
        '# Generated by scripts/test-up.ps1 for the local test stack.',
        '# Throwaway credentials for a localhost-only stack. Never reuse these,',
        '# and never copy this file to .env on a server.',
        '',
        "MYSQL_ROOT_PASSWORD=$(New-Secret 32)",
        'MYSQL_DATABASE=storefront_test',
        'MYSQL_USER=storefront',
        "MYSQL_PASSWORD=$(New-Secret 32)",
        "REDIS_PASSWORD=$(New-Secret 32)",
        '',
        'CORS_ALLOWED_ORIGINS=http://localhost:8080,http://127.0.0.1:8080',
        "JWT_SIGNING_KEY=$(New-Secret 64)",
        '',
        'ADMIN_SEED_USERNAME=admin',
        "ADMIN_SEED_PASSWORD=$(New-Secret 20)",
        'ADMIN_SEED_EMAIL=',
        '',
        'STORE_NAME=Loja de Teste',
        'STORE_CURRENCY=BRL',
        'STORE_LOCALE=pt-BR',
        'STORE_COUNTRY_CODE=BR',
        'STORE_TIME_ZONE=America/Sao_Paulo',
        'STORE_LOGO_URL=/logoFarma.png',
        'STORE_WHATSAPP_NUMBER=',
        '',
        'ANALYTICS_RAW_RETENTION_DAYS=90',
        'OTLP_ENDPOINT=',
        'OTEL_SERVICE_NAME=storefront-test'
    )

    # UTF-8 without a BOM, written through .NET rather than Set-Content:
    # PowerShell 5.1 writes UTF-16 for `>` redirection, which compose cannot
    # parse — it reads the file as binary noise and every variable comes out
    # unset.
    $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($envFile, ($lines -join "`n") + "`n", $utf8NoBom)
}
else {
    Write-Host 'Reusing the existing .env.test' -ForegroundColor Cyan
}

# --- Validate before starting anything -------------------------------------

Write-Host 'Validating the configuration...' -ForegroundColor Cyan
docker compose @composeArgs config --quiet
if ($LASTEXITCODE -ne 0) {
    Write-Host 'The configuration is invalid; nothing was started.' -ForegroundColor Red
    exit 1
}

# --- Up --------------------------------------------------------------------

Write-Host 'Building and starting (first run pulls images and can take a few minutes)...' -ForegroundColor Cyan
docker compose @composeArgs up --build -d
if ($LASTEXITCODE -ne 0) {
    Write-Host ''
    Write-Host 'The stack did not come up. Logs:' -ForegroundColor Red
    Write-Host "  docker compose $($composeArgs -join ' ') logs"
    exit 1
}

# Read back rather than reuse the generated values, so the credentials shown
# are the ones the stack actually booted with when .env.test already existed.
function Get-EnvValue {
    param([string]$Key)
    $line = Get-Content $envFile | Where-Object { $_ -match "^$([regex]::Escape($Key))=" } | Select-Object -First 1
    if ($null -eq $line) { return '(not set)' }
    $value = $line.Substring($Key.Length + 1)
    if ([string]::IsNullOrWhiteSpace($value)) { return '(empty)' }
    return $value
}

$adminUser = Get-EnvValue 'ADMIN_SEED_USERNAME'
$adminPass = Get-EnvValue 'ADMIN_SEED_PASSWORD'

Write-Host ''
Write-Host 'Test stack is up.' -ForegroundColor Green
Write-Host ''
Write-Host '  Storefront   http://localhost:8080'
Write-Host '  Admin        http://localhost:8080/login'
Write-Host '  Swagger      http://localhost:5001/swagger'
Write-Host '  Health       http://localhost:5001/health'
Write-Host ''
Write-Host "  user  $adminUser"
Write-Host "  pass  $adminPass"
Write-Host ''
Write-Host 'The credentials are in .env.test. Keep the file: the admin account is'
Write-Host 'seeded once, while the users table is empty, so deleting .env.test and'
Write-Host 'regenerating it will NOT change the password of an account that already'
Write-Host 'exists. To start over from scratch, tear down with -v first.'
Write-Host ''
Write-Host 'To follow the logs:'
Write-Host "  docker compose $($composeArgs -join ' ') logs -f"
Write-Host 'To tear it down, volumes included:'
Write-Host "  docker compose $($composeArgs -join ' ') down -v"
